version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins-local'
    build: .
    restart: 'always'
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
volumes:
  jenkins_home: